"use client";

import { useEffect, useState } from "react";
import { Cloud, Plus, Trash2, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { BANK_TRANSACTION_TYPES, CASHFLOW_BRANDS, CASHFLOW_DEPARTMENTS, CASHFLOW_TYPES, EMPTY_CASHFLOW, normalizeCashflow, safeAmount, type BankMutation, type CashflowData, type CashflowEntry } from "@/lib/cashflow";

export type CashflowPage = "cashflow" | "cashflowProjection" | "cashflowActual" | "cashflowBank";
const ALL = "__all__";
const WEEKS = Array.from({ length: 27 }, (_, index) => `Week ${index + 26}`);
const rupiah = (value: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(Number.isFinite(value) ? value : 0);
const percent = (actual: number, projection: number) => projection ? actual / projection * 100 : 0;
const status = (projection: number, actual: number) => !projection && !actual ? "Belum Ada Data" : actual <= projection ? "Aman" : "Over Budget";
const statusClass = (value: string) => value === "Aman" ? "bg-emerald-100 text-emerald-700" : value === "Over Budget" ? "bg-red-100 text-red-700" : "bg-slate-100 text-slate-600";
const emptyEntry = (): CashflowEntry => ({ id: "", brand: "", department: "", paymentItem: "", description: "", type: "", nominal: 0, date: "", week: "", source: "Manual Input", notes: "" });
const emptyBank = (): BankMutation => ({ id: "", brand: "", bank: "", company: "", date: "", financeDescription: "", paymentItem: "", department: "", projectionStatus: "Belum Dicek", transactionType: "", bankDescription: "", debit: 0, credit: 0, balance: 0, week: "", source: "Manual Input" });

export function CashflowDashboard({ page, verifyPassword }: { page: CashflowPage; verifyPassword: () => Promise<string | null> }) {
  const [data, setData] = useState<CashflowData>(EMPTY_CASHFLOW);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState("");
  useEffect(() => { fetch("/api/cashflow-data", { cache: "no-store" }).then((r) => r.json()).then((p) => setData(normalizeCashflow(p.cashflowData))).catch(() => setNotice("Data cloud tidak dapat dimuat. Empty state digunakan.")).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (loading) return; localStorage.setItem("cashflowProjectionData", JSON.stringify(data.projection)); localStorage.setItem("cashflowActualData", JSON.stringify(data.actual)); localStorage.setItem("cashflowBankMutationData", JSON.stringify(data.bankMutation)); localStorage.setItem("cashflowData", JSON.stringify(data)); }, [data, loading]);
  async function save() { const password = await verifyPassword(); if (!password) return; setSaving(true); setNotice(""); try { const response = await fetch("/api/cashflow-data", { method: "POST", headers: { "Content-Type": "application/json", "x-dashboard-password": password }, body: JSON.stringify({ cashflowData: data }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData((current) => ({ ...current, lastUpdated: payload.updatedAt })); setNotice("Cashflow berhasil disimpan ke cloud secara terpisah."); } catch (error) { setNotice(error instanceof Error ? error.message : "Save to Cloud gagal."); } finally { setSaving(false); } }
  if (loading) return <Card className="rounded-3xl"><CardContent className="p-8 text-center text-slate-500">Memuat data Cashflow...</CardContent></Card>;
  return <div className="space-y-5">{notice && <div className="rounded-2xl border border-blue-100 bg-white p-4 text-sm font-semibold text-slate-700">{notice}</div>}{page === "cashflow" ? <CashflowOverview data={data} onSave={save} saving={saving} /> : <CashflowEditor page={page} data={data} setData={setData} onSave={save} saving={saving} />}</div>;
}

function CashflowOverview({ data, onSave, saving }: { data: CashflowData; onSave: () => void; saving: boolean }) {
  const [filters, setFilters] = useState({ period: ALL, brand: ALL, week: ALL, department: ALL, type: ALL });
  const matches = (row: CashflowEntry | BankMutation) => (filters.brand === ALL || row.brand === filters.brand) && (filters.week === ALL || row.week === filters.week) && (filters.department === ALL || row.department === filters.department) && (filters.type === ALL || ("type" in row ? row.type : row.transactionType) === filters.type) && (filters.period === ALL || row.date.startsWith(filters.period));
  const projection = data.projection.filter(matches);
  const explicitActual = data.actual.filter(matches);
  const bank = data.bankMutation.filter(matches);
  const actual: CashflowEntry[] = data.actual.length ? explicitActual : bank.map((row) => ({ id: row.id, brand: row.brand, department: row.department, paymentItem: row.paymentItem, description: row.financeDescription || row.bankDescription, type: row.transactionType, nominal: safeAmount(row.credit) || safeAmount(row.debit), date: row.date, week: row.week, source: "Mutasi Bank" }));
  const totalProjection = projection.reduce((sum, row) => sum + safeAmount(row.nominal), 0); const totalActual = actual.reduce((sum, row) => sum + safeAmount(row.nominal), 0); const remaining = totalProjection - totalActual; const realization = percent(totalActual, totalProjection); const budgetStatus = status(totalProjection, totalActual);
  const group = (key: "type" | "department") => Array.from(new Set([...projection.map((r) => r[key]), ...actual.map((r) => r[key])].filter(Boolean))).map((name) => { const projected = projection.filter((r) => r[key] === name).reduce((s, r) => s + safeAmount(r.nominal), 0); const realized = actual.filter((r) => r[key] === name).reduce((s, r) => s + safeAmount(r.nominal), 0); return { name, projected, realized, difference: projected - realized }; });
  const types = group("type"), departments = group("department");
  return <><Card className="rounded-3xl"><CardContent className="flex flex-wrap gap-3 p-4">{[["period", "Filter Periode", Array.from({ length: 12 }, (_, i) => `2026-${String(i + 1).padStart(2, "0")}`)], ["brand", "Semua Brand", CASHFLOW_BRANDS], ["week", "Semua Week", WEEKS], ["department", "Semua Departemen", CASHFLOW_DEPARTMENTS], ["type", "Semua Jenis Transaksi", Array.from(new Set([...CASHFLOW_TYPES, ...BANK_TRANSACTION_TYPES]))]] .map(([key, label, values]) => <Select key={key as string} value={filters[key as keyof typeof filters]} onChange={(e) => setFilters({ ...filters, [key as string]: e.target.value })} className="h-11 min-w-40 flex-1 rounded-xl"><option value={ALL}>{label as string}</option>{(values as readonly string[]).map((v) => <option key={v}>{v}</option>)}</Select>)}<Button onClick={onSave} disabled={saving} variant="outline" className="h-11 rounded-xl font-bold"><Cloud className="h-4 w-4" /> {saving ? "Menyimpan..." : "Save to Cloud"}</Button></CardContent></Card>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Total Proyeksi", rupiah(totalProjection)], ["Total Realisasi", rupiah(totalActual)], ["Sisa Budget", rupiah(remaining)], ["% Realisasi", `${realization.toFixed(1)}%`], ["Status Budget", budgetStatus]].map(([label, value]) => <Card key={label} className="rounded-3xl"><CardContent className="p-5"><p className="text-xs font-black uppercase tracking-wider text-slate-500">{label}</p><p className="mt-3 text-xl font-black text-slate-900">{label === "Status Budget" ? <Badge className={statusClass(value)}>{value}</Badge> : value}</p></CardContent></Card>)}</div>
    <Card className="rounded-3xl"><CardHeader><CardTitle>Ringkasan Arus Kas</CardTitle><CardDescription>Perbandingan budget dan actual spending sesuai filter.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Total Budget / Proyeksi", rupiah(totalProjection)], ["Actual Spending / Realisasi", rupiah(totalActual)], ["Budget Remaining / Sisa Budget", rupiah(remaining)], ["% Realisasi", `${realization.toFixed(1)}%`], ["Status", budgetStatus]].map(([a,b]) => <div key={a} className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">{a}</p><p className="mt-2 font-black">{b}</p></div>)}</CardContent></Card>
    <Breakdown title="Detail per Jenis Biaya" heading="Jenis Biaya" rows={types} />
    <Breakdown title="Detail per Departemen" heading="Departemen" rows={departments} />
    <Card className="rounded-3xl"><CardHeader><CardTitle>Analisis Penyebab Over Budget</CardTitle></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow>{["Departemen","Proyeksi","Realisasi","Selisih","Top Penyebab Over Budget"].map((h)=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{departments.filter((r)=>r.realized>r.projected).map((r)=><TableRow key={r.name}><TableCell className="font-bold">{r.name}</TableCell><TableCell>{rupiah(r.projected)}</TableCell><TableCell>{rupiah(r.realized)}</TableCell><TableCell className="text-red-600">{rupiah(r.difference)}</TableCell><TableCell>{actual.filter((a)=>a.department===r.name).sort((a,b)=>b.nominal-a.nominal)[0]?.description || actual.filter((a)=>a.department===r.name)[0]?.paymentItem || "-"}</TableCell></TableRow>)}{!departments.some((r)=>r.realized>r.projected)&&<EmptyRow span={5}/>}</TableBody></Table></CardContent></Card></>;
}

function Breakdown({ title, heading, rows }: { title: string; heading: string; rows: { name: string; projected: number; realized: number; difference: number }[] }) { return <Card className="rounded-3xl"><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow>{[heading,"Proyeksi","Realisasi","Selisih","% Realisasi","Status"].map((h)=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r)=><TableRow key={r.name}><TableCell className="font-bold">{r.name}</TableCell><TableCell>{rupiah(r.projected)}</TableCell><TableCell>{rupiah(r.realized)}</TableCell><TableCell>{rupiah(r.difference)}</TableCell><TableCell>{percent(r.realized,r.projected).toFixed(1)}%</TableCell><TableCell><Badge className={statusClass(status(r.projected,r.realized))}>{status(r.projected,r.realized)}</Badge></TableCell></TableRow>)}{!rows.length&&<EmptyRow span={6}/>}</TableBody></Table></CardContent></Card>; }

function CashflowEditor({ page, data, setData, onSave, saving }: { page: CashflowPage; data: CashflowData; setData: (data: CashflowData) => void; onSave: () => void; saving: boolean }) {
  const isBank = page === "cashflowBank", key = page === "cashflowProjection" ? "projection" : page === "cashflowActual" ? "actual" : "bankMutation";
  const [modal, setModal] = useState(false); const [entry, setEntry] = useState<CashflowEntry>(emptyEntry); const [mutation, setMutation] = useState<BankMutation>(emptyBank);
  const rows = data[key]; const title = page === "cashflowProjection" ? "Proyeksi" : page === "cashflowActual" ? "Realisasi" : "Mutasi Bank";
  function submit() { if (isBank) { const row = { ...mutation, id: mutation.id || `mutation-${crypto.randomUUID()}` }; setData({ ...data, bankMutation: mutation.id ? data.bankMutation.map((r)=>r.id===mutation.id?row:r) : [...data.bankMutation,row] }); } else { const row = { ...entry, id: entry.id || `cashflow-${crypto.randomUUID()}` }; const current = data[key] as CashflowEntry[]; setData({ ...data, [key]: entry.id ? current.map((r)=>r.id===entry.id?row:r) : [...current,row] }); } setModal(false); }
  function remove(id: string) { if (!confirm("Hapus data ini?")) return; setData({ ...data, [key]: rows.filter((r)=>r.id!==id) }); }
  return <><Card className="rounded-3xl"><CardContent className="flex flex-wrap justify-between gap-3 p-4"><div><p className="font-black">Cashflow &gt; {title}</p><p className="text-sm text-slate-500">Input dan kelola data {title.toLowerCase()} cashflow.</p></div><div className="flex gap-2"><Button onClick={()=>{if (isBank) setMutation(emptyBank()); else setEntry(emptyEntry()); setModal(true)}} className="rounded-xl bg-blue-600"><Plus className="h-4 w-4"/> Tambah {isBank?"Mutasi Bank":`Data ${title}`}</Button><Button onClick={onSave} disabled={saving} variant="outline" className="rounded-xl"><Cloud className="h-4 w-4"/> Save to Cloud</Button></div></CardContent></Card>
  <Card className="overflow-hidden rounded-3xl"><CardContent className="max-h-[68vh] overflow-auto p-0"><Table className="min-w-max"><TableHeader className="sticky top-0 z-10 bg-white"><TableRow>{(isBank ? ["Brand","Bank/Kas","Perusahaan","Date","Keterangan Finance","Item Pembayaran","Departemen","Masuk/Tidak Masuk","Jenis Transaksi","Keterangan Bank","Debit","Kredit","Balance","Week","Source","Hapus"] : ["No","Brand","Departemen","Item Pembayaran","Deskripsi","Jenis","Nominal","Tanggal","Week",...(page==="cashflowActual"?["Source","Hapus"]:["Hapus"])]).map((h)=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((raw,index)=>isBank?<BankRow key={raw.id} row={raw as BankMutation} onEdit={()=>{setMutation(raw as BankMutation);setModal(true)}} onDelete={()=>remove(raw.id)}/>:<EntryRow key={raw.id} index={index} row={raw as CashflowEntry} actual={page==="cashflowActual"} onEdit={()=>{setEntry(raw as CashflowEntry);setModal(true)}} onDelete={()=>remove(raw.id)}/>)}{!rows.length&&<EmptyRow span={isBank?16:page==="cashflowActual"?11:10}/>}</TableBody></Table></CardContent></Card>
  {modal&&<EditorModal title={title} bank={isBank} entry={entry} setEntry={setEntry} mutation={mutation} setMutation={setMutation} onClose={()=>setModal(false)} onSave={submit}/>}</>;
}

function EntryRow({ row, index, actual, onEdit, onDelete }: { row: CashflowEntry; index:number; actual:boolean; onEdit:()=>void; onDelete:()=>void }) { return <TableRow className="cursor-pointer" onDoubleClick={onEdit}><TableCell>{index+1}</TableCell>{[row.brand,row.department,row.paymentItem,row.description,row.type,rupiah(row.nominal),row.date,row.week,...(actual?[row.source]:[])].map((v,i)=><TableCell key={i}>{v||"-"}</TableCell>)}<TableCell><Button size="sm" variant="ghost" onClick={onDelete} className="text-red-600"><Trash2 className="h-4 w-4"/></Button></TableCell></TableRow>; }
function BankRow({ row,onEdit,onDelete }:{row:BankMutation;onEdit:()=>void;onDelete:()=>void}) { const values=[row.brand,row.bank,row.company,row.date,row.financeDescription,row.paymentItem,row.department,row.projectionStatus,row.transactionType,row.bankDescription,rupiah(row.debit),rupiah(row.credit),rupiah(row.balance),row.week,row.source]; return <TableRow className="cursor-pointer" onDoubleClick={onEdit}>{values.map((v,i)=><TableCell key={i}>{v||"-"}</TableCell>)}<TableCell><Button size="sm" variant="ghost" onClick={onDelete} className="text-red-600"><Trash2 className="h-4 w-4"/></Button></TableCell></TableRow>; }

function EditorModal({ title, bank, entry, setEntry, mutation, setMutation, onClose, onSave }:{title:string;bank:boolean;entry:CashflowEntry;setEntry:(v:CashflowEntry)=>void;mutation:BankMutation;setMutation:(v:BankMutation)=>void;onClose:()=>void;onSave:()=>void}) { const fields = bank ? [["brand","Brand","select",CASHFLOW_BRANDS],["bank","Bank/Kas"],["company","Perusahaan"],["date","Date","date"],["financeDescription","Keterangan Finance"],["paymentItem","Item Pembayaran"],["department","Departemen","select",CASHFLOW_DEPARTMENTS],["projectionStatus","Masuk/Tidak Masuk","select",["Masuk Proyeksi","Tidak Masuk Proyeksi","Belum Dicek"]],["transactionType","Jenis Transaksi","select",BANK_TRANSACTION_TYPES],["bankDescription","Keterangan Bank"],["debit","Debit","number"],["credit","Kredit","number"],["balance","Balance","number"],["week","Week","select",WEEKS]] : [["brand","Brand","select",CASHFLOW_BRANDS],["department","Departemen","select",CASHFLOW_DEPARTMENTS],["paymentItem","Item Pembayaran"],["description","Deskripsi"],["type","Jenis","select",CASHFLOW_TYPES],["nominal","Nominal","number"],["date","Tanggal","date"],["week","Week","select",WEEKS],...(title==="Realisasi"?[["notes","Keterangan"]]:[])]; const value = bank ? mutation : entry; const update=(key:string,next:string)=>bank?setMutation({...mutation,[key]:["debit","credit","balance"].includes(key)?safeAmount(next):next}):setEntry({...entry,[key]:key==="nominal"?safeAmount(next):next}); return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div className="max-h-[92vh] w-full max-w-4xl overflow-auto rounded-3xl bg-white shadow-2xl"><div className="sticky top-0 z-10 flex justify-between border-b bg-white p-5"><h2 className="text-xl font-black">{value.id?"Edit":"Tambah"} {title}</h2><Button variant="ghost" size="icon" onClick={onClose}><X/></Button></div><div className="grid gap-4 p-5 sm:grid-cols-2">{fields.map(([key,label,type,options])=><label key={key as string} className="space-y-2"><span className="text-sm font-bold">{label as string}</span>{type==="select"?<Select value={String(value[key as keyof typeof value]??"")} onChange={(e)=>update(key as string,e.target.value)} className="h-11 w-full rounded-xl"><option value="">Pilih {label as string}</option>{(options as readonly string[]).map((o)=><option key={o}>{o}</option>)}</Select>:<Input type={(type as string)||"text"} min={type==="date"?"2026-01-01":undefined} max={type==="date"?"2026-12-31":undefined} value={String(value[key as keyof typeof value]??"")} onChange={(e)=>update(key as string,e.target.value)} className="h-11 rounded-xl"/>}</label>)}</div><div className="flex justify-end gap-2 border-t p-5"><Button variant="outline" onClick={onClose}>Batal</Button><Button onClick={onSave} className="bg-blue-600">Simpan</Button></div></div></div>; }
function EmptyRow({span}:{span:number}) { return <TableRow><TableCell colSpan={span} className="h-28 text-center font-semibold text-slate-500">Belum ada data. Nilai dihitung sebagai Rp 0.</TableCell></TableRow>; }
