"use client";

import { ChangeEvent, useMemo, useRef, useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Upload } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Select } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { CONTROL_OMZET_MONTHS, controlOmzetStatus, parseControlOmzetWorkbook, type ControlOmzetRow, type ControlOmzetStatus } from "@/lib/control-omzet";

const ALL = "__all__"; const GROUPS = ["1001", "Obsidian", "Resto", "Management"]; const STATUSES: ControlOmzetStatus[] = ["Aman", "Perlu Review", "Tidak Terlapor", "Lebih Terlapor"];
const COLORS = ["#2563eb", "#7c3aed", "#f97316", "#16a34a"];
const rupiah = (value: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value || 0);
const percent = (value: number) => `${new Intl.NumberFormat("id-ID", { maximumFractionDigits: 1 }).format(value || 0)}%`;
type Filters = { tahun: string; masa: string; group: string; entity: string; status: string };
function aggregate(rows: ControlOmzetRow[]) { const omzet = rows.reduce((sum, row) => sum + row.omzet, 0); const terlapor = rows.reduce((sum, row) => sum + row.terlapor, 0); return { omzet, terlapor, selisih: omzet - terlapor, persentaseTerlapor: omzet ? terlapor / omzet * 100 : 0 }; }
function badge(status: ControlOmzetStatus) { return status === "Aman" ? "bg-green-100 text-green-700" : status === "Perlu Review" ? "bg-amber-100 text-amber-700" : status === "Tidak Terlapor" ? "bg-red-100 text-red-700" : status === "Lebih Terlapor" ? "bg-violet-100 text-violet-700" : "bg-slate-100 text-slate-600"; }

export function ControlOmzetDashboard({ data, setData, saving, onSave }: { data: ControlOmzetRow[]; setData: (rows: ControlOmzetRow[]) => void; saving: boolean; onSave: () => void }) {
  const input = useRef<HTMLInputElement>(null); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [filters, setFilters] = useState<Filters>({ tahun: ALL, masa: ALL, group: ALL, entity: ALL, status: ALL });
  const entities = useMemo(() => Array.from(new Set(data.map((row) => row.entity))).filter(Boolean).sort(), [data]);
  const rows = useMemo(() => data.map((row) => ({ ...row, status: controlOmzetStatus(row) })).filter((row) => (filters.tahun === ALL || String(row.tahun) === filters.tahun) && (filters.masa === ALL || row.masa === filters.masa) && (filters.group === ALL || row.group === filters.group) && (filters.entity === ALL || row.entity === filters.entity) && (filters.status === ALL || row.status === filters.status)), [data, filters]);
  const totals = useMemo(() => aggregate(rows), [rows]);
  const monthly = CONTROL_OMZET_MONTHS.map((masa) => ({ masa: masa.slice(0, 3), ...aggregate(rows.filter((row) => row.masa === masa)) }));
  const byGroup = GROUPS.map((group) => ({ name: group, value: rows.filter((row) => row.group === group).reduce((sum, row) => sum + row.omzet, 0) })).filter((item) => item.value);
  const grouped = (key: "group" | "entity") => Array.from(new Set(rows.map((row) => row[key]))).filter(Boolean).map((name) => { const selected = rows.filter((row) => row[key] === name); const total = aggregate(selected); return { name, group: key === "entity" ? selected[0]?.group ?? "-" : "", ...total, status: controlOmzetStatus(total) }; });
  const groupTotals = grouped("group"); const entityTotals = grouped("entity"); const top = [...entityTotals].sort((a, b) => b.selisih - a.selisih).slice(0, 5);
  const update = (key: keyof Filters, value: string) => setFilters((current) => ({ ...current, [key]: value, ...(key === "group" ? { entity: ALL } : {}) }));
  function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setError(""); setMessage(""); if (!/\.xlsx?$/i.test(file.name)) { setError("Format Excel Control Omzet tidak sesuai."); event.target.value = ""; return; } const reader = new FileReader(); reader.onload = () => { try { const parsed = parseControlOmzetWorkbook(reader.result as ArrayBuffer); setData(parsed); setMessage(parsed.length ? `${parsed.length} baris Control Omzet berhasil dimuat. Data lama telah diganti.` : "Excel kosong. Data Control Omzet telah dikosongkan."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Format Excel Control Omzet tidak sesuai."); } finally { event.target.value = ""; } }; reader.onerror = () => { setError("Format Excel Control Omzet tidak sesuai."); event.target.value = ""; }; reader.readAsArrayBuffer(file); }
  const Empty = () => <div className="grid h-64 place-items-center rounded-2xl border border-dashed border-slate-300 text-sm font-semibold text-slate-500">Belum ada data Control Omzet.</div>;
  const SummaryTable = ({ entity = false }: { entity?: boolean }) => { const list = entity ? entityTotals : groupTotals; return <Card className="rounded-3xl shadow-sm"><CardHeader><CardTitle>Total per {entity ? "Entity" : "Group"}</CardTitle></CardHeader><CardContent className="overflow-auto">{list.length ? <Table><TableHeader><TableRow>{[entity ? "Entity" : "Group", ...(entity ? ["Group"] : []), "Total Omzet", "Total Terlapor", "Selisih", "% Terlapor", "Status"].map((h) => <TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{list.map((item) => <TableRow key={item.name}><TableCell className="font-bold">{item.name}</TableCell>{entity && <TableCell>{item.group}</TableCell>}<TableCell>{rupiah(item.omzet)}</TableCell><TableCell>{rupiah(item.terlapor)}</TableCell><TableCell>{rupiah(item.selisih)}</TableCell><TableCell>{percent(item.persentaseTerlapor)}</TableCell><TableCell><Badge className={badge(item.status)}>{item.status}</Badge></TableCell></TableRow>)}</TableBody></Table> : <Empty />}</CardContent></Card>; };
  return <div className="space-y-6">
    <Card className="rounded-3xl shadow-sm"><CardContent className="flex flex-wrap items-center gap-3 p-4">{([["tahun", "Semua Tahun", ["2026"]], ["masa", "Semua Masa Pajak", [...CONTROL_OMZET_MONTHS]], ["group", "Semua Group", GROUPS], ["entity", "Semua Entity", entities.filter((entity) => filters.group === ALL || data.some((row) => row.entity === entity && row.group === filters.group))], ["status", "Semua Status", STATUSES]] as [keyof Filters, string, readonly string[]][]).map(([key, label, options]) => <Select key={key} value={filters[key]} onChange={(e) => update(key, e.target.value)} className="h-11 min-w-40 flex-1 rounded-2xl"><option value={ALL}>{label}</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</Select>)}<Button onClick={() => input.current?.click()} className="h-11 rounded-2xl bg-blue-600 font-bold"><Upload className="h-4 w-4" /> Upload Excel</Button><Button onClick={onSave} disabled={saving} variant="outline" className="h-11 rounded-2xl font-bold">Save to Cloud</Button><input ref={input} type="file" accept=".xlsx,.xls" onChange={upload} hidden /></CardContent></Card>
    {message && <div className="rounded-2xl border border-green-200 bg-green-50 p-4 text-sm font-semibold text-green-700">{message}</div>}{error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{[["Total Omzet", rupiah(totals.omzet)], ["Total Terlapor", rupiah(totals.terlapor)], ["Total Selisih", rupiah(totals.selisih)], ["Persentase Terlapor", percent(totals.persentaseTerlapor)], ["Jumlah Entity", new Set(rows.map((r) => r.entity)).size], ["Jumlah Masa", new Set(rows.map((r) => `${r.tahun}-${r.masa}`)).size]].map(([label, value]) => <Card key={label} className="rounded-3xl shadow-sm"><CardContent className="p-5"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-2 break-words text-xl font-black">{value}</p></CardContent></Card>)}</section>
    <section className="grid gap-6 xl:grid-cols-2"><Chart title="Omzet vs Terlapor per Bulan">{rows.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={monthly}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="masa" /><YAxis tickFormatter={(v) => `${Math.round(v / 1e6)} jt`} /><Tooltip formatter={(v: number) => rupiah(v)} /><Legend /><Bar dataKey="omzet" name="Omzet" fill="#2563eb" /><Bar dataKey="terlapor" name="Terlapor" fill="#16a34a" /></BarChart></ResponsiveContainer> : <Empty />}</Chart><Chart title="Komposisi Omzet per Group">{byGroup.length ? <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={byGroup} dataKey="value" nameKey="name" innerRadius="50%" outerRadius="75%">{byGroup.map((item, i) => <Cell key={item.name} fill={COLORS[i % COLORS.length]} />)}</Pie><Tooltip formatter={(v: number) => rupiah(v)} /><Legend /></PieChart></ResponsiveContainer> : <Empty />}</Chart><div className="xl:col-span-2"><Chart title="Top 5 Entity dengan Selisih Terbesar">{top.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={top} layout="vertical"><CartesianGrid strokeDasharray="3 3" /><XAxis type="number" tickFormatter={(v) => `${Math.round(v / 1e6)} jt`} /><YAxis type="category" dataKey="name" width={170} tick={{ fontSize: 11 }} /><Tooltip formatter={(v: number) => rupiah(v)} /><Bar dataKey="selisih" name="Selisih" fill="#f97316" /></BarChart></ResponsiveContainer> : <Empty />}</Chart></div></section>
    <Card className="rounded-3xl shadow-sm"><CardHeader><CardTitle>Tabel Detail Control Omzet</CardTitle></CardHeader><CardContent className="overflow-auto">{rows.length ? <Table><TableHeader><TableRow>{["Masa Pajak", "Group", "Entity", "Omzet", "Terlapor", "Selisih", "% Terlapor", "Status"].map((h) => <TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row, i) => <TableRow key={`${row.entity}-${row.masa}-${i}`}><TableCell>{row.masa} {row.tahun}</TableCell><TableCell>{row.group}</TableCell><TableCell className="min-w-56 font-semibold">{row.entity}</TableCell><TableCell>{rupiah(row.omzet)}</TableCell><TableCell>{rupiah(row.terlapor)}</TableCell><TableCell>{rupiah(row.selisih)}</TableCell><TableCell>{percent(row.persentaseTerlapor)}</TableCell><TableCell><Badge className={badge(row.status)}>{row.status}</Badge></TableCell></TableRow>)}</TableBody></Table> : <Empty />}</CardContent></Card>
    <section className="grid gap-6 xl:grid-cols-2"><SummaryTable /><SummaryTable entity /></section>
  </div>;
}
function Chart({ title, children }: { title: string; children: React.ReactNode }) { return <Card className="rounded-3xl shadow-sm"><CardHeader><CardTitle>{title}</CardTitle><CardDescription>Data mengikuti filter aktif.</CardDescription></CardHeader><CardContent className="h-80">{children}</CardContent></Card>; }
