"use client";

import { ChangeEvent, FormEvent, useEffect, useRef, useState } from "react";
import * as XLSX from "xlsx";
import { BarChart3, Building2, CheckSquare, Database, Download, Edit3, Eye, FileArchive, FileSpreadsheet, FileText, FolderOpen, Menu, Plus, ReceiptText, StickyNote, Store, Trash2, Upload, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { cn } from "@/lib/utils";

type PageType = "Summary" | "Table" | "Notes" | "Checklist" | "Document Storage";
type IconName = "Receipt" | "File" | "Archive" | "Store" | "Building" | "Spreadsheet" | "Chart" | "Notes" | "Checklist" | "Folder";
type TaxType = "PPN Keluaran" | "PPN Masukan" | "PM Tidak Dikreditkan" | "KB/LB PPN" | "PPh 21" | "PPh 23" | "PPh Final 4(2)" | "PB1" | "PPh UMKM";
type SidebarItem = { id: string; label: string; pageType: PageType; icon: IconName; order: number; active: boolean; system?: boolean };
type TaxRecord = { id: string; companyName: string; taxPeriod: string; taxType: TaxType; dpp: number; taxAmount: number; ntpn: string; ntpd: string; sourceSheet: string; sourceRow: number; note: string; createdAt: string; updatedAt: string };
type Pb1SalesRecord = { id: string; companyName: string; period: string; description: string; salesMembership: number; salesReportedMembership: number; netSales: number; taxPb1: number; channels: Record<string, number>; sourceSheet: string; sourceRow: number; createdAt: string; updatedAt: string };
type StoredDocument = { id: string; fileName: string; fileUrl: string; fileSize: number; category: string; companyName: string; taxPeriod: string; taxType: string; uploadedAt: string; createdAt: string };

type Status = "Terverifikasi" | "Belum Lengkap" | "Lebih Bayar" | "Nihil" | "Kompensasi";

const DB_NAME = "tax-coordinator-storage";
const DOC_STORE = "pdf-documents";
const SIDEBAR_KEY = "tax-coordinator-sidebars-v2";
const DOCUMENT_META_KEY = "tax-coordinator-document-metadata-v2";
const TAX_RECORD_KEY = "tax-coordinator-tax-records-v2";
const PB1_KEY = "tax-coordinator-pb1-sales-v2";
const ALL = "Semua";
const SHEETS = ["PPH-Resto", "PB1 - PGO", "PPH-Obsidian", "PPN-1001", "PPH-1001"];
const docCategories = ["SPT Masa PPN", "SPT Masa PPh 21", "SPT Masa PPh Unifikasi", "PB1", "PPh UMKM", "Bukti Potong", "Bukti Bayar", "NTPN", "Surat DJP", "Dokumen Pendukung"];
const iconMap = { Receipt: ReceiptText, File: FileText, Archive: FileArchive, Store, Building: Building2, Spreadsheet: FileSpreadsheet, Chart: BarChart3, Notes: StickyNote, Checklist: CheckSquare, Folder: FolderOpen };
const iconOptions = Object.keys(iconMap) as IconName[];
const pageTypes: PageType[] = ["Summary", "Table", "Notes", "Checklist", "Document Storage"];
const defaultSidebars: SidebarItem[] = [
  { id: "ppn", label: "PPN", pageType: "Table", icon: "Receipt", order: 1, active: true, system: true },
  { id: "pph-21", label: "PPh Pasal 21", pageType: "Table", icon: "File", order: 2, active: true, system: true },
  { id: "pph-unifikasi", label: "PPh Unifikasi", pageType: "Table", icon: "Archive", order: 3, active: true, system: true },
  { id: "pb1", label: "PB1", pageType: "Table", icon: "Store", order: 4, active: true, system: true },
  { id: "umkm", label: "UMKM", pageType: "Table", icon: "Building", order: 5, active: true, system: true },
  { id: "dokumen-pajak", label: "Dokumen Pajak", pageType: "Document Storage", icon: "Folder", order: 6, active: true, system: true },
];
const now = "2026-06-17T00:00:00.000Z";
const seedTaxRecords: TaxRecord[] = [
  ...["Jan-26", "Feb-26", "Mar-26", "Apr-26"].flatMap((p, i) => {
    const out = [56500100, 44020000, 38130000, 0][i], input = [42100000, 31850000, 26200000, 12584131][i], n = ["18E965BMSRJ4L749", "9A976684GAFNKVEQ", "001403ISSLB147J8", ""][i];
    return [rec("CV SEPULUH JANUARI SUKSES", p, "PPN Keluaran", out * 10, out, n, "", "PPN-1001", i + 2, ""), rec("CV SEPULUH JANUARI SUKSES", p, "PPN Masukan", input * 10, input, n, "", "PPN-1001", i + 2, i === 3 ? "Masa Februari LB; kompensasi lebih bayar dari masa sebelumnya" : ""), rec("CV SEPULUH JANUARI SUKSES", p, "KB/LB PPN", 0, out - input, n, "", "PPN-1001", i + 2, "")];
  }),
  ...["PT MAKAN SETIAP HARI", "PT MINUM SETIAP HARI", "PT PRIMA GLOBAL OBSIDIAN", "PT SEJUTA TOKO BERSAMA", "PT GLOBAL SEHAT BERKARYA", "PT MIMAMA LAKU SELALU", "CV SEPULUH JANUARI SUKSES", "CV SERIBU TOKO SUKSES", "CV EVENT"].flatMap((c, i) => [rec(c, "Jan-26", "PPh 21", 80000000 + i * 3500000, 2400000 + i * 120000, i % 3 ? `NTPN21${i}JAN26` : "", "", i === 2 ? "PPH-Obsidian" : i > 5 ? "PPH-1001" : "PPH-Resto", i + 3, i % 3 ? "" : "NTPN tidak ada karena kompensasi lebih bayar dari masa sebelumnya"), rec(c, "Jan-26", "PPh 23", 12000000 + i * 700000, 240000 + i * 14000, `UNI${i}JAN26`, "", i === 2 ? "PPH-Obsidian" : i > 5 ? "PPH-1001" : "PPH-Resto", i + 3, i % 2 ? "NTPN digunakan untuk PPh PS23 dan PPh Final 4(2)" : ""), rec(c, "Jan-26", "PPh Final 4(2)", 18000000 + i * 900000, 1800000 + i * 90000, i % 2 ? `UNI${i}JAN26` : "", "", i === 2 ? "PPH-Obsidian" : i > 5 ? "PPH-1001" : "PPH-Resto", i + 3, i % 2 ? "NTPN digunakan untuk PPh PS23 dan PPh Final 4(2)" : "Masa Februari LB"), rec(c, "Jan-26", "PB1", 45000000 + i * 1000000, 4500000 + i * 100000, "", `NTPD-PB1-${i}`, "PPH-Resto", i + 3, ""), rec(c, "Jan-26", "PPh UMKM", 30000000 + i * 800000, 150000 + i * 4000, i % 4 ? `UMKM${i}JAN26` : "", "", i > 5 ? "PPH-1001" : "PPH-Resto", i + 3, "")]),
];
const seedPb1: Pb1SalesRecord[] = ["Jan-26", "Feb-26", "Mar-26"].map((p, i) => ({ id: `pb1-pgo-${i}`, companyName: "PT PRIMA GLOBAL OBSIDIAN", period: p, description: "Omzet restoran dan membership", salesMembership: 125000000 + i * 8000000, salesReportedMembership: 123500000 + i * 7000000, netSales: 220000000 + i * 15000000, taxPb1: 22000000 + i * 1500000, channels: { "EDC BCA": 85000000 + i * 5000000, OCBC: 42000000, Cash: 18000000, "Bank Transfer": 76000000, "Potongan EDC": -1200000 }, sourceSheet: "PB1 - PGO", sourceRow: i + 2, createdAt: now, updatedAt: now }));
function rec(companyName: string, taxPeriod: string, taxType: TaxType, dpp: number, taxAmount: number, ntpn: string, ntpd: string, sourceSheet: string, sourceRow: number, note: string): TaxRecord { return { id: `${companyName}-${taxPeriod}-${taxType}-${sourceRow}`.replace(/\s+/g, "-"), companyName, taxPeriod, taxType, dpp, taxAmount, ntpn, ntpd, sourceSheet, sourceRow, note, createdAt: now, updatedAt: now }; }
function safeParse<T>(value: string | null, fallback: T): T { if (!value) return fallback; try { return JSON.parse(value) as T; } catch { return fallback; } }
function fmt(value: number) { return new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value); }
function bytes(value: number) { return `${(value / 1024 / 1024).toFixed(2)} MB`; }
function sum<T>(rows: T[], getter: (row: T) => number) { return rows.reduce((a, r) => a + getter(r), 0); }
function status(row: { taxAmount: number; ntpn?: string; ntpd?: string; note?: string }): Status { const note = (row.note ?? "").toLowerCase(); if (note.includes("kompensasi")) return "Kompensasi"; if (row.taxAmount < 0) return "Lebih Bayar"; if (!row.taxAmount) return "Nihil"; return row.ntpn || row.ntpd ? "Terverifikasi" : "Belum Lengkap"; }
function variant(s: Status) { return s === "Terverifikasi" ? "success" : s === "Belum Lengkap" ? "warning" : s === "Lebih Bayar" ? "destructive" : "secondary"; }
function monthPeriod(v: unknown) { if (typeof v === "number" && v > 40000) { const d = XLSX.SSF.parse_date_code(v); return new Date(d.y, d.m - 1, d.d).toLocaleDateString("en-US", { month: "short", year: "2-digit" }).replace(" ", "-"); } return String(v ?? "").trim() || "-"; }
function num(v: unknown) { return Number(String(v ?? "0").replace(/[^0-9.-]/g, "")) || 0; }
function csv(name: string, rows: Record<string, unknown>[]) { const keys = Object.keys(rows[0] ?? { empty: "" }); const body = [keys.join(","), ...rows.map((r) => keys.map((k) => `"${String(r[k] ?? "").replace(/"/g, '""')}"`).join(","))].join("\n"); const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([body], { type: "text/csv" })); a.download = name; a.click(); }
async function openDb() { return new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open(DB_NAME, 1); request.onupgradeneeded = () => request.result.createObjectStore(DOC_STORE); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function putPdf(id: string, file: File) { const db = await openDb(); return new Promise<void>((resolve, reject) => { const tx = db.transaction(DOC_STORE, "readwrite"); tx.objectStore(DOC_STORE).put(file, id); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); }
async function getPdfUrl(id: string) { const db = await openDb(); return new Promise<string>((resolve, reject) => { const tx = db.transaction(DOC_STORE, "readonly"); const req = tx.objectStore(DOC_STORE).get(id); req.onsuccess = () => resolve(URL.createObjectURL(req.result as Blob)); req.onerror = () => reject(req.error); }); }
async function deletePdf(id: string) { const db = await openDb(); return new Promise<void>((resolve, reject) => { const tx = db.transaction(DOC_STORE, "readwrite"); tx.objectStore(DOC_STORE).delete(id); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); }

export function TaxCoordinatorDashboard() {
  const [mobileOpen, setMobileOpen] = useState(false), [activeId, setActiveId] = useState("dashboard"), [message, setMessage] = useState("");
  const [selectedCompany, setSelectedCompany] = useState(ALL), [selectedPeriod, setSelectedPeriod] = useState(ALL), [selectedTax, setSelectedTax] = useState(ALL), [selectedSheet, setSelectedSheet] = useState(ALL), [search, setSearch] = useState(""), [categoryFilter, setCategoryFilter] = useState(ALL);
  const [sidebars, setSidebars] = useState(defaultSidebars), [taxRecords, setTaxRecords] = useState(seedTaxRecords), [pb1Sales, setPb1Sales] = useState(seedPb1), [documents, setDocuments] = useState<StoredDocument[]>([]);
  const [docDraft, setDocDraft] = useState({ category: docCategories[0], companyName: ALL, taxPeriod: ALL, taxType: "PPN" });
  const [draft, setDraft] = useState<SidebarItem>({ id: "", label: "", pageType: "Summary", icon: "Chart", order: 7, active: true });
  const [editingId, setEditingId] = useState<string | null>(null);
  const pdfRef = useRef<HTMLInputElement>(null), excelRef = useRef<HTMLInputElement>(null);
  useEffect(() => { setSidebars(safeParse(localStorage.getItem(SIDEBAR_KEY), defaultSidebars)); setDocuments(safeParse(localStorage.getItem(DOCUMENT_META_KEY), [])); setTaxRecords(safeParse(localStorage.getItem(TAX_RECORD_KEY), seedTaxRecords)); setPb1Sales(safeParse(localStorage.getItem(PB1_KEY), seedPb1)); }, []);
  useEffect(() => { localStorage.setItem(SIDEBAR_KEY, JSON.stringify(sidebars)); }, [sidebars]); useEffect(() => { localStorage.setItem(DOCUMENT_META_KEY, JSON.stringify(documents)); }, [documents]); useEffect(() => { localStorage.setItem(TAX_RECORD_KEY, JSON.stringify(taxRecords)); }, [taxRecords]); useEffect(() => { localStorage.setItem(PB1_KEY, JSON.stringify(pb1Sales)); }, [pb1Sales]);
  const companies = [ALL, ...Array.from(new Set([...taxRecords.map((r) => r.companyName), ...pb1Sales.map((r) => r.companyName), ...documents.map((d) => d.companyName)].filter(Boolean))).sort()];
  const periods = [ALL, ...Array.from(new Set([...taxRecords.map((r) => r.taxPeriod), ...pb1Sales.map((r) => r.period), ...documents.map((d) => d.taxPeriod)].filter(Boolean))).sort()];
  const sheets = [ALL, ...SHEETS];
  const filteredTax = taxRecords.filter((r) => (selectedCompany === ALL || r.companyName === selectedCompany) && (selectedPeriod === ALL || r.taxPeriod === selectedPeriod) && (selectedTax === ALL || r.taxType === selectedTax) && (selectedSheet === ALL || r.sourceSheet === selectedSheet) && `${r.companyName} ${r.taxPeriod} ${r.taxType} ${r.ntpn} ${r.ntpd} ${r.note}`.toLowerCase().includes(search.toLowerCase()));
  const filteredPb1 = pb1Sales.filter((r) => (selectedCompany === ALL || r.companyName === selectedCompany) && (selectedPeriod === ALL || r.period === selectedPeriod) && (selectedSheet === ALL || r.sourceSheet === selectedSheet));
  const filteredDocs = documents.filter((d) => (selectedCompany === ALL || d.companyName === selectedCompany) && (selectedPeriod === ALL || d.taxPeriod === selectedPeriod) && (selectedTax === ALL || d.taxType === selectedTax) && (categoryFilter === ALL || d.category === categoryFilter) && `${d.fileName} ${d.category} ${d.companyName}`.toLowerCase().includes(search.toLowerCase()));
  const byType = (t: TaxType) => filteredTax.filter((r) => r.taxType === t);
  const docsUnlinked = documents.filter((d) => d.companyName === ALL || d.taxPeriod === ALL).length;
  const duplicateNtpn = Object.entries(filteredTax.filter((r) => r.ntpn).reduce((a, r) => ({ ...a, [r.ntpn]: new Set([...(a[r.ntpn] ?? []), r.taxType]) }), {} as Record<string, Set<TaxType>>)).filter(([, v]) => v.size > 1).map(([k]) => k);
  const summaryRows = Array.from(new Map(filteredTax.map((r) => [`${r.companyName}|${r.taxPeriod}`, { companyName: r.companyName, taxPeriod: r.taxPeriod }])).values()).map((base) => { const rows = filteredTax.filter((r) => r.companyName === base.companyName && r.taxPeriod === base.taxPeriod); const val = (t: TaxType) => sum(rows.filter((r) => r.taxType === t), (r) => r.taxAmount); return { ...base, ppnKeluaran: val("PPN Keluaran"), ppnMasukan: val("PPN Masukan"), kbLb: val("KB/LB PPN"), pph21: val("PPh 21"), pph23: val("PPh 23"), pphFinal: val("PPh Final 4(2)"), pb1: val("PB1"), umkm: val("PPh UMKM"), statusNtpn: rows.every((r) => !r.taxAmount || r.ntpn || r.ntpd) ? "Terverifikasi" : "Belum Lengkap", note: rows.map((r) => r.note).filter(Boolean).join("; ") }; });
  function importExcel(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const wb = XLSX.read(reader.result, { type: "array" }); const rows: TaxRecord[] = []; const pb1: Pb1SalesRecord[] = []; wb.SheetNames.filter((n) => SHEETS.includes(n)).forEach((sheet) => { const raw = XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[sheet], { header: 1, blankrows: false }); let lastCompany = sheet === "PPN-1001" ? "CV SEPULUH JANUARI SUKSES" : sheet === "PB1 - PGO" ? "PT PRIMA GLOBAL OBSIDIAN" : ""; raw.slice(1).forEach((r, idx) => { const company = String(r[0] || lastCompany || "").trim(); if (company) lastCompany = company; const period = monthPeriod(r[1] ?? r[0]); const note = r.map(String).find((c) => /kompensasi|lebih bayar|lb|ntpn/i.test(c)) ?? ""; if (sheet === "PB1 - PGO") pb1.push({ id: crypto.randomUUID(), companyName: "PT PRIMA GLOBAL OBSIDIAN", period, description: String(r[2] ?? "Imported PB1"), salesMembership: num(r[3]), salesReportedMembership: num(r[4]), netSales: num(r[5]), taxPb1: num(r[6]), channels: { "EDC BCA": num(r[7]), OCBC: num(r[8]), Cash: num(r[9]), "Bank Transfer": num(r[10]), "Potongan EDC": num(r[11]) }, sourceSheet: sheet, sourceRow: idx + 2, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });
        else ["PPh 21", "PPh 23", "PPh Final 4(2)", "PB1", "PPh UMKM"].forEach((t, j) => rows.push(rec(lastCompany, period, t as TaxType, num(r[2 + j * 3]), num(r[3 + j * 3]), String(r[4 + j * 3] ?? ""), t === "PB1" ? String(r[4 + j * 3] ?? "") : "", sheet, idx + 2, note)));
      }); }); if (rows.length) setTaxRecords(rows); if (pb1.length) setPb1Sales(pb1); setMessage(`Import Excel selesai: ${rows.length} tax_records dan ${pb1.length} pb1_sales_records dari ${wb.SheetNames.filter((n) => SHEETS.includes(n)).join(", ")}.`); }; reader.readAsArrayBuffer(file); event.target.value = ""; }
  async function uploadPdf(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (file.type !== "application/pdf" && !file.name.toLowerCase().endsWith(".pdf")) { setMessage("File ditolak: hanya PDF yang dapat diupload."); event.target.value = ""; return; } const id = crypto.randomUUID(); await putPdf(id, file); setDocuments((cur) => [{ id, fileName: file.name, fileUrl: `indexeddb://${DOC_STORE}/${id}`, fileSize: file.size, category: docDraft.category, companyName: docDraft.companyName, taxPeriod: docDraft.taxPeriod, taxType: docDraft.taxType, uploadedAt: new Date().toISOString(), createdAt: new Date().toISOString() }, ...cur]); event.target.value = ""; }
  async function preview(doc: StoredDocument, download = false) { const url = await getPdfUrl(doc.id); if (download) { const a = document.createElement("a"); a.href = url; a.download = doc.fileName; a.click(); } else window.open(url, "_blank", "noopener,noreferrer"); }
  function saveSidebar(e: FormEvent) { e.preventDefault(); const id = editingId ?? draft.label.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); setSidebars((cur) => editingId ? cur.map((i) => i.id === editingId ? { ...draft, id, system: i.system } : i) : [...cur, { ...draft, id, order: Number(draft.order) || cur.length + 1 }]); setDraft({ id: "", label: "", pageType: "Summary", icon: "Chart", order: sidebars.length + 2, active: true }); setEditingId(null); }
  const HeaderFilters = <div className="grid gap-3 lg:grid-cols-4 xl:grid-cols-7"><Select value={selectedCompany} onChange={(e) => { setSelectedCompany(e.target.value); setDocDraft((d) => ({ ...d, companyName: e.target.value })); }} className="bg-white">{companies.map((x) => <option key={x}>{x}</option>)}</Select><Select value={selectedPeriod} onChange={(e) => { setSelectedPeriod(e.target.value); setDocDraft((d) => ({ ...d, taxPeriod: e.target.value })); }} className="bg-white">{periods.map((x) => <option key={x}>{x}</option>)}</Select><Select value={selectedTax} onChange={(e) => setSelectedTax(e.target.value)} className="bg-white">{[ALL, "PPN Keluaran", "PPN Masukan", "KB/LB PPN", "PPh 21", "PPh 23", "PPh Final 4(2)", "PB1", "PPh UMKM"].map((x) => <option key={x}>{x}</option>)}</Select><Select value={selectedSheet} onChange={(e) => setSelectedSheet(e.target.value)} className="bg-white">{sheets.map((x) => <option key={x}>{x}</option>)}</Select><Button onClick={() => excelRef.current?.click()}><Upload className="h-4 w-4" />Upload Excel</Button><Button variant="outline" onClick={() => csv(`${activeId}.csv`, summaryRows as unknown as Record<string, unknown>[])}><Download className="h-4 w-4" />Export CSV</Button><Input ref={excelRef} type="file" accept=".xlsx,.xls" className="hidden" onChange={importExcel} /></div>;
  const Sidebar = <aside className="flex h-full flex-col bg-slate-950 px-4 py-6 text-white"><div className="mb-8 flex items-center gap-3 rounded-2xl bg-white/5 p-3"><div className="rounded-xl bg-blue-600 p-3"><ReceiptText /></div><div><p className="font-black">Tax Coordinator</p><p className="text-xs text-slate-400">Control Dashboard</p></div></div><nav className="space-y-1"><button className={cn("menu", activeId === "dashboard" && "bg-blue-600 text-white")} onClick={() => setActiveId("dashboard")}><BarChart3 className="h-4 w-4" />Dashboard</button>{sidebars.filter((i) => i.active).sort((a, b) => a.order - b.order).map((i) => { const Icon = iconMap[i.icon]; return <button key={i.id} className={cn("menu", activeId === i.id && "bg-blue-600 text-white")} onClick={() => setActiveId(i.id)}><Icon className="h-4 w-4" />{i.label}</button>; })}</nav><p className="mt-auto rounded-xl bg-white/5 p-3 text-xs text-slate-300">Data permanen disimpan di localStorage dan PDF di IndexedDB browser.</p></aside>;
  return <main className="min-h-screen bg-slate-100 lg:grid lg:grid-cols-[280px_1fr]"><style>{`.menu{display:flex;width:100%;align-items:center;gap:.75rem;border-radius:.75rem;padding:.75rem;text-align:left;font-size:.875rem;font-weight:700;color:#cbd5e1}.menu:hover{background:rgba(255,255,255,.1);color:white}`}</style><div className="hidden lg:block">{Sidebar}</div>{mobileOpen && <div className="fixed inset-0 z-50 grid grid-cols-[280px_1fr] bg-slate-950/50 lg:hidden">{Sidebar}<button onClick={() => setMobileOpen(false)} className="p-4 text-white"><X /></button></div>}<section className="min-w-0 p-4 sm:p-6 lg:p-8"><header className="mb-6 space-y-4"><div className="flex gap-3"><Button variant="outline" size="icon" className="lg:hidden" onClick={() => setMobileOpen(true)}><Menu /></Button><div><h1 className="text-3xl font-black text-slate-950">{activeId === "dashboard" ? "Executive Tax Control" : sidebars.find((s) => s.id === activeId)?.label}</h1><p className="text-sm font-medium text-slate-500">PPN, PPh 21, PPh Unifikasi, PB1, UMKM, Dokumen Pajak, import Excel, dan sidebar manual.</p></div></div>{HeaderFilters}</header>{message && <div className="mb-4 rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm font-semibold text-blue-700">{message}</div>}
  {activeId === "dashboard" && <><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["Total PPN Keluaran", sum(byType("PPN Keluaran"), r=>r.taxAmount)], ["Total PPN Masukan", sum(byType("PPN Masukan"), r=>r.taxAmount)], ["Total KB/LB PPN", sum(byType("KB/LB PPN"), r=>r.taxAmount)], ["Total PM Tidak Dikreditkan", sum(byType("PM Tidak Dikreditkan"), r=>r.taxAmount)], ["Total PPh Pasal 21", sum(byType("PPh 21"), r=>r.taxAmount)], ["Total PPh Pasal 23", sum(byType("PPh 23"), r=>r.taxAmount)], ["Total PPh Final 4(2)", sum(byType("PPh Final 4(2)"), r=>r.taxAmount)], ["Total PB1", sum(byType("PB1"), r=>r.taxAmount)+sum(filteredPb1,r=>r.taxPb1)], ["Total PPh UMKM", sum(byType("PPh UMKM"), r=>r.taxAmount)], ["Jumlah perusahaan", new Set(filteredTax.map(r=>r.companyName)).size], ["Jumlah masa pajak", new Set(filteredTax.map(r=>r.taxPeriod)).size], ["NTPN terisi", filteredTax.filter(r=>r.ntpn||r.ntpd).length], ["Belum memiliki NTPN", filteredTax.filter(r=>r.taxAmount && !r.ntpn && !r.ntpd).length], ["Dokumen terupload", documents.length], ["Dokumen belum terkait", docsUnlinked]].map(([label, val]) => <Card key={label as string}><CardContent className="p-5"><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-black">{typeof val === "number" && String(label).startsWith("Total") ? fmt(val) : val}</p></CardContent></Card>)}</section><DataTable title="Tax Summary by Company" rows={summaryRows} columns={["companyName","taxPeriod","ppnKeluaran","ppnMasukan","kbLb","pph21","pph23","pphFinal","pb1","umkm","statusNtpn","note"]} /></>}
  {activeId === "ppn" && <><Cards data={[["Total DPP Pajak Keluaran", sum(byType("PPN Keluaran"), r=>r.dpp)], ["Total PPN Keluaran", sum(byType("PPN Keluaran"), r=>r.taxAmount)], ["Total DPP Pajak Masukan", sum(byType("PPN Masukan"), r=>r.dpp)], ["Total PPN Masukan", sum(byType("PPN Masukan"), r=>r.taxAmount)], ["Total PM Tidak Dikreditkan", sum(byType("PM Tidak Dikreditkan"), r=>r.taxAmount)], ["Total KB/LB", sum(byType("KB/LB PPN"), r=>r.taxAmount)], ["Masa ada NTPN", byType("KB/LB PPN").filter(r=>r.ntpn).length], ["Masa belum NTPN", byType("KB/LB PPN").filter(r=>!r.ntpn).length]]}/><DataTable title="PPN-1001" rows={byType("PPN Keluaran").map(r=>({perusahaan:r.companyName,masa:r.taxPeriod,pkDpp:r.dpp,pkPpn:r.taxAmount,pmDpp:byType("PPN Masukan").find(x=>x.taxPeriod===r.taxPeriod)?.dpp,pmPpn:byType("PPN Masukan").find(x=>x.taxPeriod===r.taxPeriod)?.taxAmount,pmtdDpp:byType("PM Tidak Dikreditkan").find(x=>x.taxPeriod===r.taxPeriod)?.dpp,pmtdPpn:byType("PM Tidak Dikreditkan").find(x=>x.taxPeriod===r.taxPeriod)?.taxAmount,kbLb:byType("KB/LB PPN").find(x=>x.taxPeriod===r.taxPeriod)?.taxAmount,ntpn:r.ntpn,keterangan:r.note,status:status(r)}))} columns={["perusahaan","masa","pkDpp","pkPpn","pmDpp","pmPpn","pmtdDpp","pmtdPpn","kbLb","ntpn","keterangan","status"]}/></>}
  {activeId === "pph-21" && <TaxPage title="PPh Pasal 21" rows={byType("PPh 21")} />}{activeId === "pph-unifikasi" && <><Cards data={[["Total PPh 23",sum(byType("PPh 23"),r=>r.taxAmount)],["Total PPh Final 4(2)",sum(byType("PPh Final 4(2)"),r=>r.taxAmount)],["Total DPP PPh 23",sum(byType("PPh 23"),r=>r.dpp)],["Total DPP PPh Final 4(2)",sum(byType("PPh Final 4(2)"),r=>r.dpp)],["NTPN terisi",byType("PPh 23").concat(byType("PPh Final 4(2)")).filter(r=>r.ntpn).length],["Belum NTPN",byType("PPh 23").concat(byType("PPh Final 4(2)")).filter(r=>!r.ntpn).length]]}/><p className="my-3 rounded-xl bg-amber-50 p-3 text-sm font-semibold text-amber-700">Catatan NTPN ganda: {duplicateNtpn.join(", ") || "Tidak ada pada filter saat ini"}</p><TaxPage title="PPh Unifikasi" rows={byType("PPh 23").concat(byType("PPh Final 4(2)"))} /></>}
  {activeId === "pb1" && <><Cards data={[["Total Net Sales",sum(filteredPb1,r=>r.netSales)],["Total Tax PB1",sum(filteredPb1,r=>r.taxPb1)+sum(byType("PB1"),r=>r.taxAmount)],["Channel sales terbesar",Object.entries(filteredPb1.reduce((a,r)=>{Object.entries(r.channels).forEach(([k,v])=>a[k]=(a[k]??0)+v);return a;},{} as Record<string,number>)).sort((a,b)=>b[1]-a[1])[0]?.[0]??"-"],["Selisih Membership",sum(filteredPb1,r=>r.salesMembership-r.salesReportedMembership)]]}/><DataTable title="PB1 - PGO Detail Omzet" rows={filteredPb1.map(r=>({...r,...r.channels}))} columns={["companyName","period","salesMembership","salesReportedMembership","netSales","taxPb1","EDC BCA","OCBC","Cash","Bank Transfer","Potongan EDC","description"]}/><TaxPage title="PB1 dari PPH-Resto" rows={byType("PB1")} /></>}
  {activeId === "umkm" && <TaxPage title="PPh UMKM" rows={byType("PPh UMKM")} />}
  {activeId === "dokumen-pajak" && <><Card><CardHeader><CardTitle>Upload Dokumen PDF</CardTitle><CardDescription>Validasi hanya PDF, metadata lengkap, preview, download, delete, search dan filter.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-5"><Select value={docDraft.category} onChange={e=>setDocDraft({...docDraft,category:e.target.value})}>{docCategories.map(c=><option key={c}>{c}</option>)}</Select><Input value={docDraft.companyName} onChange={e=>setDocDraft({...docDraft,companyName:e.target.value})} placeholder="Perusahaan"/><Input value={docDraft.taxPeriod} onChange={e=>setDocDraft({...docDraft,taxPeriod:e.target.value})} placeholder="Masa pajak"/><Input value={docDraft.taxType} onChange={e=>setDocDraft({...docDraft,taxType:e.target.value})} placeholder="Jenis pajak"/><Button onClick={()=>pdfRef.current?.click()}><Upload className="h-4 w-4"/>Upload PDF</Button><Input ref={pdfRef} type="file" accept="application/pdf,.pdf" className="hidden" onChange={uploadPdf}/></CardContent></Card><div className="mt-4 grid gap-3 md:grid-cols-[1fr_220px_auto]"><Input placeholder="Search dokumen" value={search} onChange={e=>setSearch(e.target.value)}/><Select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}>{[ALL,...docCategories].map(c=><option key={c}>{c}</option>)}</Select><Button onClick={()=>csv("dokumen-pajak.csv", filteredDocs as unknown as Record<string, unknown>[])}><Download className="h-4 w-4"/>Export CSV</Button></div><Card className="mt-4"><CardContent className="p-0"><Table><TableHeader><TableRow>{["Nama file","Kategori","Perusahaan","Masa","Jenis","Tanggal","Ukuran","URL","Aksi"].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{filteredDocs.map(d=><TableRow key={d.id}><TableCell>{d.fileName}</TableCell><TableCell>{d.category}</TableCell><TableCell>{d.companyName}</TableCell><TableCell>{d.taxPeriod}</TableCell><TableCell>{d.taxType}</TableCell><TableCell>{new Date(d.uploadedAt).toLocaleString("id-ID")}</TableCell><TableCell>{bytes(d.fileSize)}</TableCell><TableCell className="text-xs">{d.fileUrl}</TableCell><TableCell><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>preview(d)}><Eye className="h-4 w-4"/></Button><Button size="sm" variant="outline" onClick={()=>preview(d,true)}><Download className="h-4 w-4"/></Button><Button size="sm" variant="destructive" onClick={async()=>{await deletePdf(d.id);setDocuments(cur=>cur.filter(x=>x.id!==d.id));}}><Trash2 className="h-4 w-4"/></Button></div></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></>}
  {!defaultSidebars.some(s=>s.id===activeId) && activeId!=="dashboard" && <DataTable title={sidebars.find(s=>s.id===activeId)?.label ?? "Sidebar"} rows={summaryRows} columns={["companyName","taxPeriod","statusNtpn","note"]}/>}<SidebarManager sidebars={sidebars} setSidebars={setSidebars} draft={draft} setDraft={setDraft} editingId={editingId} setEditingId={setEditingId} saveSidebar={saveSidebar} /></section></main>;
}
function Cards({ data }: { data: [string, number | string][] }) { return <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{data.map(([label, val]) => <Card key={label}><CardContent className="p-5"><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-black">{typeof val === "number" && !label.includes("Jumlah") && !label.includes("NTPN") && !label.includes("Masa") ? fmt(val) : val}</p></CardContent></Card>)}</section>; }
function TaxPage({ title, rows }: { title: string; rows: TaxRecord[] }) { return <><Cards data={[[`Total DPP ${title}`, sum(rows,r=>r.dpp)],[`Total Pajak ${title}`,sum(rows,r=>r.taxAmount)],["Jumlah perusahaan",new Set(rows.map(r=>r.companyName)).size],["Jumlah NTPN terisi",rows.filter(r=>r.ntpn||r.ntpd).length],["Data tanpa NTPN",rows.filter(r=>r.taxAmount&&!r.ntpn&&!r.ntpd).length],["Status",rows.every(r=>!r.taxAmount||r.ntpn||r.ntpd)?"Lengkap":"Belum lengkap"]]}/><DataTable title={title} rows={rows.map(r=>({perusahaan:r.companyName,masaPajak:r.taxPeriod,jenisPajak:r.taxType,dpp:r.dpp,pajak:r.taxAmount,ntpn:r.ntpn||r.ntpd,sourceSheet:r.sourceSheet,keterangan:r.note,status:status(r)}))} columns={["perusahaan","masaPajak","jenisPajak","dpp","pajak","ntpn","sourceSheet","keterangan","status"]}/></>; }
function DataTable({ title, rows, columns }: { title: string; rows: Record<string, unknown>[]; columns: string[] }) { return <Card className="mt-6"><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{rows.length} baris data normalized.</CardDescription></CardHeader><CardContent className="overflow-auto"><Table><TableHeader><TableRow>{columns.map(c=><TableHead key={c}>{c}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={i}>{columns.map(c=><TableCell key={c} className="whitespace-nowrap">{c.toLowerCase().includes("status") ? <Badge variant={variant(String(r[c]) as Status)}>{String(r[c]??"")}</Badge> : typeof r[c] === "number" ? fmt(r[c] as number) : String(r[c]??"")}</TableCell>)}</TableRow>)}</TableBody></Table></CardContent></Card>; }
function SidebarManager(props: { sidebars: SidebarItem[]; setSidebars: React.Dispatch<React.SetStateAction<SidebarItem[]>>; draft: SidebarItem; setDraft: (v: SidebarItem) => void; editingId: string | null; setEditingId: (v: string | null) => void; saveSidebar: (e: FormEvent) => void }) { const { sidebars, setSidebars, draft, setDraft, editingId, setEditingId, saveSidebar } = props; return <Card className="mt-6"><CardHeader><CardTitle className="flex items-center gap-2"><Database className="h-5 w-5"/>Sidebar Management</CardTitle><CardDescription>Tambah, edit nama, hapus, urutan, icon, aktif/nonaktif, dan tipe halaman manual.</CardDescription></CardHeader><CardContent><form onSubmit={saveSidebar} className="mb-5 grid gap-3 md:grid-cols-[1fr_170px_150px_100px_120px]"><Input required placeholder="Nama sidebar" value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})}/><Select value={draft.pageType} onChange={e=>setDraft({...draft,pageType:e.target.value as PageType})}>{pageTypes.map(t=><option key={t}>{t}</option>)}</Select><Select value={draft.icon} onChange={e=>setDraft({...draft,icon:e.target.value as IconName})}>{iconOptions.map(i=><option key={i}>{i}</option>)}</Select><Input type="number" value={draft.order} onChange={e=>setDraft({...draft,order:Number(e.target.value)})}/><Button type="submit"><Plus className="h-4 w-4"/>{editingId?"Simpan":"Tambah"}</Button></form><Table><TableHeader><TableRow>{["Order","Name","Type","Icon","Status","Aksi"].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{[...sidebars].sort((a,b)=>a.order-b.order).map(i=><TableRow key={i.id}><TableCell>{i.order}</TableCell><TableCell>{i.label}</TableCell><TableCell>{i.pageType}</TableCell><TableCell>{i.icon}</TableCell><TableCell><Badge variant={i.active?"success":"secondary"}>{i.active?"Aktif":"Nonaktif"}</Badge></TableCell><TableCell><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setSidebars(cur=>cur.map(x=>x.id===i.id?{...x,active:!x.active}:x))}>{i.active?"Nonaktifkan":"Aktifkan"}</Button><Button size="sm" variant="outline" onClick={()=>{setDraft(i);setEditingId(i.id);}}><Edit3 className="h-4 w-4"/></Button><Button size="sm" variant="destructive" disabled={i.system} onClick={()=>setSidebars(cur=>cur.filter(x=>x.id!==i.id))}><Trash2 className="h-4 w-4"/></Button></div></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>; }
